### ISSUE TITLE
Support ignoring null attributes

### ISSUE THREAD

**Issue by ddolcimascolo** [davidcalhoun/jstoxml#10]
The library should support (through a configuration parameter) ignoring null attributes in the generated XML output.

**Comment by davidcalhoun** [comment]
Thanks so much for the PR, and apologies for not getting it this sooner.  I'm going to close this one out, as there's already a way to achieve this desired output:

```js
```

**Comment by davidcalhoun** [comment]
Thanks so much for this PR, and apologies for the delay (only about 5 years late, haha).

Going to close this one, since this output can be achieved with the following:

```js
toXML({
  _name: 'foo',
  _attrs: {
    attr1: 'v1',
    attr2: 'null'
  },
  _content: 'bar'
});
```

I can definitely see a use for some sort of mapper function though, which would let folks customize stuff like this.  Maybe something like this:

```js
toXML({
  _name: 'foo',
  _attrs: {
    attr1: 'v1',
    attr2: 'null'
  },
  _content: 'bar'
},
{
  attributeMapper: attr => attr === null ? 'null' ? null;
});
```

Will consider that for future features!

**Comment by davidcalhoun** [comment]
In v3 you can now achieve this by using the [config option](https://github.com/davidcalhoun/jstoxml#configuration-object-options-passed-as-second-parameter-to-toxml) `attributeFilter` and writing your own supplied filter function to remove attribute entries, e.g.

```js
const content = {
    _name: 'foo',
    _attrs: {
        attr1: 'v1',
        attr2: null
    },
    _content: 'bar'
};
const config = { attributeFilter: (key, val) => val === null };
toXML(content, config);
// -> '<foo attr1="v1">bar</foo>'
```
