### ISSUE TITLE
Why is your module better than others js to xml converters?

### ISSUE THREAD

**Issue by devotis** [davidcalhoun/jstoxml#16]
I need to build a relatively simple XML document with some hierarchy and some attributes from a JS object. I stand now before choosing one of these modules:
https://github.com/davidcalhoun/jstoxml
https://github.com/soldair/node-jsontoxml
https://github.com/QuickenLoans/node-easyxml
https://github.com/michaelkourlas/node-js2xmlparser

Why should I pick this module instead of one of the others?

_Disclaimer: I posted the same question as an issue on the other repositories too._

**Comment by davidcalhoun** [comment]
Thanks @jeremyosborne!  Sorry for finally only now getting to this haha.

I built this tool because I wanted something that would convert to XML in the way I wanted, e.g. in the simplest possible way.  I think other folks have different ideas of how things should work, that ok.  Use whatever tool works for you.
