### ISSUE TITLE
Vulnerability: special characters should be escaped by default

### ISSUE THREAD

**Issue by wetneb** [davidcalhoun/jstoxml#41]
By default, this package [does not escape XML characters](https://github.com/davidcalhoun/jstoxml/issues/4#issuecomment-19165730):
```
jstoxml.toXML({
  foo: '&'
}
// Output: <foo>&</foo>
```

This is dangerous behaviour, since it means invalid XML can be output, causing injection vulnerabilities.

As a user, I would expect this package to escape strings by default. If there is a need to disable escaping, this could be done in the config, but that should not be the default behaviour.

**Comment by davidcalhoun** [comment]
Thank you for the heads up!  That seems reasonable that escaping `&` should be the default behavior.  It looks like it [should also be default behavior](https://www.w3.org/TR/xml11/#syntax) to escape `<` and `>`.

I'll look to add this and publish it as a new `minor` version, since it will be a backwards-compatible change.

**Comment by wetneb** [comment]
Thanks a lot, that would be fantastic!

I think it is a bit more than `<`, `>` and `&`: for instance, in XML attributes, you need to escape at least `"` (but I haven't checked if it is done already).

**Comment by davidcalhoun** [comment]
Thanks again!  Entities are now escaped by default in `v2.0.0`, along with `"` in attributes.  Note that I added some checks to make sure things won't be double-encoded.

Decided to make this a new major version in the end because though this change is backwards compatible, it does in fact require a code change to return to the old behavior, which is indeed a breaking change.
