### ISSUE TITLE
Required escaping missing in version 2

### ISSUE THREAD

**Issue by Allain55** [davidcalhoun/jstoxml#43]
Hi, v2 doesn't escape the '&' sign everywhere, but '&' needs to be always escaped

For example: 
`"capacit&eacute;"`

Result in v1 (as it should be):
`"capacit&amp;eacute;"`

Result in v2 is unchanged, not escaped

In v1 I use these filters:
```
'<' : '&lt;',
'>' : '&gt;',
'"' : '&quot;',
'\'': '&apos;',
'&' : '&amp;'
```

In v2 using the same settings doesn't work

For reference see:
https://www.freeformatter.com/xml-escape.html

Related to #41 

> I added some checks to make sure things won't be double-encoded.

Maybe this caused the problem?

**Comment by davidcalhoun** [comment]
Hi, thank you for the heads up!  That is indeed what's happening - `jstoxml` sees that `&eacute;` (`é`) is already entity encoded, and it's leaving it as-is.  The same thing happens if it runs across `&amp;` (`&`) - because it wouldn't make sense to output `&amp;amp;`.

I am not sure what's going on in your use case, but I could see that it may be useful to force turning off the double-encoding check.

**Comment by Allain55** [comment]
How about disallow double-encoding only for these values:
```
&amp; (&)
&lt; (<)
&gt; (>)
&quot; (")
&apos; (\)
```

**Comment by davidcalhoun** [comment]
Sorry for the delay!  You can now achieve these sort of results by [passing in a custom contentMap() function](https://github.com/davidcalhoun/jstoxml#configuration-object-options-passed-as-second-parameter-to-toxml) which runs after the the replacements have been made.  In your case you should be able to do something like this:

```js
toXML(obj, {
  contentMap: (val) => val.replaceAll('&', '&amp;')
});
```
