### ISSUE TITLE
Problem with self-closing tags

### ISSUE THREAD

**Issue by ShelterUA** [davidcalhoun/jstoxml#61]
Hello, I have problem with self-closing tags. When I use _selfCloseTag parameter with value false, It's doesn't work, empty tags don't change to <tag></tag> and still stay like <tag />. Please check dist/jstoxml.js line 345, I think here must be conf._selfCloseTag.

**Comment by davidcalhoun** [comment]
Thanks for the heads up.  Could you please provide a small code sample that shows the output and what you expect the output to be?

**Comment by ShelterUA** [comment]
CODE:
let json = {
        req: {
            tag1: 'text1',
            tag2: '',
            tag3: 'text2',
            tag4: 'text3',
            tag5: 'text4'
        }
    };

let xmlOptions = {
    header: true,
    _selfCloseTag: false
};

console.log(toXML(json, xmlOptions));

OUTPUT:
<?xml version="1.0" encoding="UTF-8"?><req><tag1>text1</tag1><tag2/><tag3>text2</tag3><tag4>text3</tag4><tag5>text4</tag5></req>

EXPECT:
<?xml version="1.0" encoding="UTF-8"?><req><tag1>text1</tag1><tag2></tag2><tag3>text2</tag3><tag4>text3</tag4><tag5>text4</tag5></req>

**Comment by davidcalhoun** [comment]
Thank you for the sample code, that helped a lot!  It turns out the readme was outdated.  I ended up adding a [new config option](https://github.com/davidcalhoun/jstoxml#configuration-object-options-passed-as-second-parameter-to-toxml) called `selfCloseTags` to a new release - `3.2.0`.  After updating to the new version, if you change `_selfCloseTag` to `selfCloseTags` you should get the output you expect!

```diff
let json = {
        req: {
            tag1: 'text1',
            tag2: '',
            tag3: 'text2',
            tag4: 'text3',
            tag5: 'text4'
        }
    };

let xmlOptions = {
    header: true,
-    _selfCloseTag: false
+    selfCloseTags: false
};
```

**Comment by ShelterUA** [comment]
Yes it works! Thank you very much! :)

**Comment by davidcalhoun** [comment]
Great, good stuff!
